version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    volumes:
      - ./models:/app/models:ro
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - BACKEND_URL=${BACKEND_URL}
    depends_on:
      - backend
    ports:
      - "8501:8501"
