[project]
name = "ml_ops_project"
version = "0.1.0"

# --- Ruff ---
[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]
exclude = ["notebooks/**"]

# --- Black ---
[tool.black]
line-length = 100
target-version = ["py311"]
extend-exclude = "notebooks/"

# --- isort ---
[tool.isort]
profile = "black"
skip_glob = ["notebooks/*"]
